In [19]:
import pandas as pd
import numpy as np
import os
from nltk.tokenize import word_tokenize
from string import punctuation

**In this project about 18 million pair of sentences will be used from this tsv files**

/kaggle/input/c4200m/C4_200M.tsv-00000-of-00010

In [ ]:
tsv_data1 = pd.read_csv('/kaggle/input/c4200m/C4_200M.tsv-00000-of-00010', sep='\t')

In [28]:
tsv_data1.columns

Index(['Bitcoin is for $7,094 this morning, which CoinDesk says.', 'Bitcoin goes for $7,094 this morning, according to CoinDesk.'], dtype='object')

In [ ]:
# Load the input values incorrect grammer sentences
x = tsv_data1['Bitcoin is for $7,094 this morning, which CoinDesk says.'].to_numpy()

# Load the labels correct grammer sentences
y = tsv_data1['Bitcoin goes for $7,094 this morning, according to CoinDesk.'].to_numpy()

**Showing sample of data using pandas module**

In [25]:
inp_lbl = {'Input': x[0:10], 'Labels': y[0:10]}
df = pd.DataFrame(inp_lbl)
df.style


**Convert letters of sentences to lowercase letters and Find missing values and delete them from arrays**

Note this missing valuse equal to nan from float dtype so lower case convert will not work with it

In [29]:
print(f'Number of elements in the input is: {x.shape}')
print('----------------------------------------------')
print(f'Number of elements in the labels is: {y.shape}')

Number of elements in the input is: (18385502,)
----------------------------------------------
Number of elements in the labels is: (18385502,)

In [ ]:
del_list = []
for i in range(0,18386521):
    try:
        x[i] = x[i].lower()
        y[i] = y[i].lower()
    except:
        del_list.append(i)

In [ ]:
x = np.delete(x, del_list)
y = np.delete(y, del_list)

In [30]:
print(f'Number of elements in the input is: {x.shape}')
print('----------------------------------------------')
print(f'Number of elements in the labels is: {y.shape}')

Number of elements in the input is: (18385502,)
----------------------------------------------
Number of elements in the labels is: (18385502,)

In [ ]:
# Check for success of the process and remove unneeded elements
unneed=[]
for i in range (0, 18386441):
    if (not (x[i].islower())) or (not (y[i].islower())):
      unneed.append(i)

In [ ]:
# Delete unneeded elements
x = np.delete(x, unneed)
y = np.delete(y, unneed)

In [31]:
print(f'Number of elements in the input is: {x.shape}')
print('----------------------------------------------')
print(f'Number of elements in the labels is: {y.shape}')

Number of elements in the input is: (18385502,)
----------------------------------------------
Number of elements in the labels is: (18385502,)

In [ ]:
saved_data = {'Input': x[0:18385502], 'Labels': y[0:18385502]}
df = pd.DataFrame(saved_data)
df.to_csv('Grammer_sentences.csv', index=False)

In [15]:
csv_data = pd.read_csv('/kaggle/working/Grammer_sentences.csv')

In [17]:
x = csv_data['Input'].to_numpy()
y = csv_data['Labels'].to_numpy()

**Remove the punctuation from the corpus**

In [27]:
def remove_punct(sentence):
    sentence = word_tokenize(sentence)
    filtered_sentence = []
    for w in sentence:
        if w not in punctuation:
            filtered_sentence.append(w)
            
    return ' '.join(filtered_sentence)

In [34]:
for i in range(0, 18385502):
    x[i] = remove_punct(x[i])
    y[i] = remove_punct(y[i])
    print(f'\rNumber of sentence: {i:08}', end='')

Number of sentence: 18385501

In [37]:
saved_data = {'Input': x[0:18385502], 'Labels': y[0:18385502]}
df = pd.DataFrame(saved_data)
df.to_csv('Grammer_sentences_v2.csv', index=False)

In [38]:
csv_data = pd.read_csv('/kaggle/working/Grammer_sentences_v2.csv')

x = csv_data['Input'].to_numpy()
y = csv_data['Labels'].to_numpy()

**Making dictionary for encoding**